### ISSUE TITLE
In latest update of tabview youtube i was getting random stuck/freeze at youtube pages idk why so pull its update cautiously is what i will advice

### ISSUE THREAD

**Issue by HakaishinShwet** [tabview-youtube/Tabview-YouTube-Totara#1]
i am currently using totara and its working fine but previously i used to use tabview original one through violent monkey userscript but after recent auto update of the script i am unable to browse in my account pages but strange thing is that if i run without login it works so just wanted to inform this here so that you pull updates from main repo carefully so that it doesnt mess up things :-))  @cyfung1031

**Comment by HakaishinShwet** [comment]
closing now as this was just to inform you about this

**Comment by cyfung1031** [comment]
Yes. Since 2024/6, fundamental problems occur in the original Tabview youtube.
This script will replace the original Tabview youtube.
(Currently, there are just some main features implemented)
