### ISSUE TITLE
Hmm joke? Or Bugs?

### ISSUE THREAD

**Issue by Dark3n89** [tabview-youtube/Tabview-YouTube-Totara#2]
Hmmm too much bla bla and = 0% injected.

![image](https://github.com/user-attachments/assets/3f30ace5-6774-45a0-b4a9-da63e0891cf9)

**Comment by cyfung1031** [comment]
???
Could you update the script to the latest version and try again?

https://update.greasyfork.org/scripts/501249/Tabview%20YouTube%20Totara.user.js

Current latest: v5.0.022
