### ISSUE TITLE
🐍 Bug: Left border missing

### ISSUE THREAD

**Issue by rahaaatul** [tabview-youtube/Tabview-YouTube-Totara#4]
![image](https://github.com/user-attachments/assets/46e05674-7f48-4973-9b30-c9ec6f163170)

**Comment by cyfung1031** [comment]
which browser are you using?
make sure you have only enabled "YouTube Tabview Totara" not the old version.

**Comment by rahaaatul** [comment]
> which browser are you using? 

Microsoft Edge `Version 131.0.2903.70 (Official build) (64-bit)`

> make sure you have only enabled "YouTube Tabview Totara" not the old version.

Yes, I made sure. I disabled all other scripts and styles.

> If you have other extensions / userscripts / userstyles, disable them first to test if there is any conflict.

I can only think of _Enhancer for YouTube_ which alters YouTube CSS; I disabled it, but it was still the same.

I tried _totara_ again and the border is there. I don't know what happened.
